Repository tryber/sd-010-a-project-frontend-online-store, pull requests merged in 2021-05, with the labels that each got.

#12 Main group 17 - Req1
  package-lock.json
  src/services/api.js
Labels: code-review

#14 [Requisito 01] - Murilo Gonçalves - Implemente o módulo de acesso à api do Mercado Livre
  package-lock.json
  src/services/api.js
Labels: code-review

#24 [Group 12] Feat: Requirement 2
  package-lock.json
  src/App.js
  src/Pages/Home.js
Labels: code-review

#25 [Group 19] [Murilo Gonçalves] - Requisito 02 - Crie uma página de listagem de produtos vazia
  src/App.js
  src/index.js
  src/pages/Home.js
Labels: code-review

#38 Grupo 16 - Implementaçao do requisito 1 - fetch API
  src/services/api.js
Labels: code-review

#48 feat: Name implementation
  src/App.js
Labels: code-review

#45 [Group 15] - requisito 1
  package-lock.json
  src/services/api.js
Labels: code-review

#10 [GRUPO-24] [REQ-1] Implementa API
  src/services/api.js
Labels: code-review

#43 requisito 1 aprovado no teste
  package-lock.json
  src/services/api.js
Labels: code-review

#67 Main group 17 - Re4
  package-lock.json
  package.json
  src/components/CategoriesList.jsx
  src/components/Loading.jsx
  src/components/index.js
  src/pages/ProductList.jsx
Labels: code-review

#59 Main group 11 requisito 02
  package-lock.json
  src/App.js
  src/Pages/ProductList.jsx
Labels: code-review

#3 [Group 8] Requisito 1
  package-lock.json
  src/App.js
  src/services/api.js
Labels: code-review, enhancement

#13 [Group 8] Requisito 02
  package-lock.json
  src/App.css
  src/App.js
  src/components/Routes.jsx
  src/components/SearchBar.jsx
Labels: code-review, enhancement

#22 feat: requirement 1-5
  package-lock.json
  src/App.css
  src/App.js
  src/assets/icon.svg
  src/components/Category.js
  src/components/InputSearch.js
  src/components/Product.js
  src/components/ShoppingCart.js
  src/services/api.js
Labels: code-review

#87 Lucaspedroso req3
  package-lock.json
  package.json
  public/images/shopping-basket.jpg
  src/App.js
  src/images/shopping-basket.jpg
  src/pages/ProductList.jsx
  src/pages/ShoppingCart.jsx
Labels: code-review

#82 [Grupo 26] requisito 5
  package-lock.json
  src/components/ListItems.js
  src/components/ProductCard.js
  src/pages/Main.js
Labels: code-review

#123 [Group 12] Requirement 4
  src/App.css
  src/App.js
  src/Components/Category.jsx
  src/Components/Loading.jsx
  src/Css/home.css
  src/Pages/Home.js
  src/index.css
  src/services/api.js
  src/styles/home.css
Labels: code-review

#79 [Group 10] Req 1 - Done
  src/App.js
  src/services/api.js
Labels: code-review

#113 [Grupo 4] Requisito 3 ✔️
  src/App.js
  src/components/CartButton.jsx
  src/pages/Cart.jsx
  src/pages/Home.jsx
Labels: code-review

#124 [Group 24] [Req 5] Listagem de Produtos com filtro
  src/Components/ListagemProdutos.jsx
  src/Components/ProductCard.jsx
Labels: code-review

#148 Main group 6 requisito 5
  src/__tests__/requirement03.test.js
  src/__tests__/requirement06.test.js
  src/__tests__/requirement07.test.js
  src/__tests__/requirement08.test.js
  src/__tests__/requirement09.test.js
  src/__tests__/requirement10.test.js
  src/__tests__/requirement11.test.js
  src/__tests__/requirement12.test.js
  src/__tests__/requirement13.test.js
  src/__tests__/requirement14.test.js
  src/__tests__/requirement15.test.js
  src/components/Categories.jsx
  src/components/ProductCard.jsx
  src/components/ProductList.jsx
  src/components/ProductNotFound.jsx
  src/components/SearchBar.jsx
  src/pages/Home.jsx
  src/services/api.js
Labels: code-review

#151 [Group 10] - Requirements 3, 4 and 5.
  src/App.js
  src/components/CategoriesList.jsx
  src/components/Home.jsx
  src/components/ProductCard.jsx
  src/pages/Cart.jsx
Labels: code-review

#126 [grupo 23] requisito 5
  src/App.js
  src/services/ProductCard.js
  src/services/input.js
Labels: code-review

#142 [Group 24] [Req 6] Implementa Filtro por Categoria
  src/Components/Categories.jsx
  src/Components/ListagemProdutos.jsx
Labels: code-review

#97 Main group 14 req 03
  src/App.css
  src/App.js
  src/imagens/shoppingCart.svg
  src/pages/Home.jsx
  src/pages/ShoppingCart.jsx
Labels: code-review

#162 Requisito 6
  src/__tests__/requirement06.test.js
  src/components/Categories.jsx
  src/pages/Home.jsx
Labels: code-review

#173 [Group 10] Req 6 - implements a filter category function
  package-lock.json
  src/components/CategoriesList.jsx
  src/components/Home.jsx
Labels: code-review

#137 Main group 13 requirement10
  src/App.css
  src/App.js
  src/components/Category.js
  src/components/InputSearch.js
  src/components/Product.js
  src/components/ProductDetails.js
  src/components/ShoppingCart.js
Labels: code-review

#181 [ Group 12 ] Requirement 5
  src/Components/CardItem.jsx
  src/Components/Category.jsx
  src/Pages/Home.js
  src/services/api.js
Labels: code-review

#183 [Group-8] req-03
  .gitignore
  package-lock.json
  package.json
  src/components/Routes.jsx
  src/components/SearchBar.jsx
  src/components/ShoppingCart.jsx
Labels: code-review, enhancement

#174 [Main Group 19] - Murilo Gonçaves - Requirement 05 - Liste os produtos buscados por termos, com os dados resumidos, associados a esses termos
  src/components/Categories.js
  src/components/Product.js
  src/components/ProductList.js
  src/components/SearchBar.js
  src/index.js
  src/pages/Home.css
  src/pages/Home.js
Labels: code-review

#196 [Group 24] [Req 8] Adiciona Produto no Carrinho a Partir da Listagem De Produtos
  src/App.js
  src/Components/ListagemProdutos.jsx
  src/Components/ProductCard.jsx
  src/Pages/ShoppingCart.jsx
  src/Pages/ShoppintCart.js
Labels: code-review

#211 [Group 10] - Feat: requirement 7
  src/App.js
  src/components/Home.jsx
  src/components/ProductCard.jsx
  src/pages/ProductDetail.jsx
Labels: code-review

#216 [Main Group 19] - Murilo Gonçalves - Requirement 06 - Selecione uma categoria e mostre somente os produtos daquela categoria
  src/components/Categories.js
  src/pages/Home.js
Labels: code-review

#228 [CaioOK & MaxRudim] - Requirement07 - Adicione produtos a partir da tela de listagem de produtos
  src/App.js
  src/components/Product.js
  src/pages/ProductDetail.js
Labels: code-review

#230 [Group 24] [Req 9]
  src/App.js
  src/Components/Details.jsx
Labels: code-review

#168 [ GRUPO 5 ] Tela com a exibição detalhada do um produto clicado
  src/App.js
  src/pages/Home/components/CardProduct.js
  src/pages/Home/components/ProductDetails.js
Labels: code-review

#229 [Group 6] - Requisito 7, agr vai com fé em Deus
  src/App.js
  src/__tests__/requirement07.test.js
  src/components/ProductCard.jsx
  src/components/ProductInfo.jsx
  src/pages/Home.jsx
  src/pages/ProductDetail.jsx
  src/services/api.js
Labels: code-review

#232 [Main group 14] Requisito 7
  README.md
  package-lock.json
  src/App.js
  src/components/ProductCard.jsx
  src/pages/Home.jsx
  src/pages/ProductDetail.jsx
  src/services/itemApi.js
Labels: code-review

#236 [Group 15] - Requisito 11
  src/pages/ProductDetails.jsx
Labels: code-review

#220 [Group 1] Fix Problems and Style Code
  src/components/Product.js
  src/components/SideBar.js
  src/pages/Home.js
  src/services/api.js
Labels: bug

#231 [Group 24] [Req 10]
  src/Pages/ShoppingCart.jsx
Labels: code-review

#207 [Group 8] req 05
  public/index.html
  src/App.css
  src/App.js
  src/components/CategoryList.jsx
  src/components/Header.jsx
  src/components/Home.jsx
  src/components/ProductCard.jsx
  src/components/Products.jsx
  src/components/Routes.jsx
  src/components/SearchBar.jsx
  src/img/car-trybe.png
  src/services/api.js
Labels: enhancement

#245 [Main Group 19] - Murilo Gonçalves, Roberto Natividade - Requirement 08 - Adicione produtos a partir da tela de listagem de produtos
  src/App.js
  src/components/Product.js
  src/components/ProductList.js
  src/pages/Cart.css
  src/pages/Cart.js
  src/pages/Home.js
Labels: code-review

#240 Conserta bug no requisito 11 - completo
  src/__tests__/requirement11.test.js
  src/components/UserReview.jsx
  src/pages/Home.jsx
  src/pages/ProductDetail.jsx
Labels: code-review

#242 [Group 1] Requisito 11
  .gitignore
  src/App.css
  src/components/comment/ProductEvaluationForm.js
  src/components/comment/RatingStar.js
  src/components/comment/StarIcon.js
Labels: enhancement

#246 [Group 12] Requirement 7
  src/App.js
  src/Components/CardItem.jsx
  src/Pages/Home.js
  src/Pages/ProductDetails.js
  src/styles/home.css
Labels: code-review

#255 [Group 1] requisito 11 - integrateção de comentarios com produto
  src/pages/ProductDetails.js
Labels: enhancement

#270 [Group 10] Req 8 - Incompleted Requirement
  src/App.js
  src/components/Home.jsx
  src/components/ProductCard.jsx
  src/pages/Cart.jsx
Labels: code-review

#272 [Group 10] Feat: requirement 11
  src/components/RatingForm.jsx
  src/pages/ProductDetail.jsx
Labels: code-review

#260 [Grupo 26] - Requisito 11
  package-lock.json
  package.json
  src/components/Form/Form.css
  src/components/Form/Form.js
  src/components/Form/Rating.js
  src/components/ListItems.js
  src/components/ProductCard.js
  src/pages/ProductDetails.js
Labels: code-review

#278 [group-15]-req12
  src/App.js
  src/components/CartItem.jsx
  src/pages/Cart.jsx
  src/pages/Checkout.jsx
  src/services/data.js
Labels: code-review

#268 [GRUPO-5] Permitir adicionar o produto ao carrinho a partir da tela de exibição detalhada.
  src/App.js
  src/pages/Home/components/CardProduct.js
  src/pages/Home/components/ProductDetails.js
Labels: code-review

#264 feat: requirement 15
  src/components/Product.js
Labels: code-review

#295 [Group12] Requirement 11
  src/Components/Star.jsx
  src/Pages/ProductDetails.js
  src/styles/ProductDetails.css
  src/styles/Star.css
Labels: code-review

#176 [GRUPO 5] Na página do Carrinho, mostrar a lista de produtos adicionados, o valor total e permitir a manipulação da sua quantidade.
  src/App.js
  src/pages/Home/components/CardProduct.js
  src/pages/Home/components/ProductDetails.js
  src/pages/Home/index.js
  src/pages/ShoppingCart.js
Labels: code-review

#288 [group-15]-styles-global
  public/index.html
  src/App.js
  src/components/CardProduct/index.jsx
  src/components/CardProduct/styles.module.css
  src/components/CartItem/index.jsx
  src/components/CartItem/styles.module.css
  src/index.css
  src/pages/styles.module.css
  src/styles/globals.css
Labels: code-review

#308 [Group 6] - corrige erro no log de proptypes e adiciona o preço total ao carrinho
  src/pages/ShoppingCart.jsx
Labels: code-review

#318 [Group 10] Req 8 - show on Cart just one title per item and its quantity.
  src/App.js
  src/components/CategoriesList.jsx
  src/components/Home.jsx
  src/pages/Cart.jsx
Labels: code-review

#313 Group 17 [refatoração utilizando localStorage]
  src/App.js
  src/components/Evaluation.jsx
  src/components/Header.jsx
  src/components/ShoppingCartItem.jsx
  src/pages/Home.jsx
  src/pages/ProductDetails.jsx
  src/pages/ShoppingCart.jsx
Labels: code-review

#322 [Group 10] Feat: Requirement 9
  src/App.js
  src/pages/ProductDetail.jsx
Labels: code-review

#265 [Main group 14] requisito 11
  package-lock.json
  package.json
  src/App.css
  src/components/ReviewForm.jsx
  src/imagens/starEmpty.png
  src/imagens/starSolid.png
  src/pages/ProductDetail.jsx
Labels: code-review

#311 [ GRUPO 5 ] Adicionar formulário para avaliar e comentar acerca de um produto em sua tela de exibição detalhada
  src/App.js
  src/pages/Home/components/ProductDetails.js
  src/pages/ProductDetails/components/ReviewFields.js
  src/pages/ProductDetails/index.js
Labels: code-review

#247 Main group 14 req 09
  src/App.js
  src/components/Button.jsx
  src/components/FilterCategory.jsx
  src/components/FrontPage.jsx
  src/components/ProductCard.jsx
  src/imagens/backArrow.svg
  src/pages/Home.jsx
  src/pages/ProductDetail.jsx
  src/pages/ShoppingCart.jsx
  src/services/api.js
  src/services/localStorage.js
  src/styles/FrontPage.css
  src/styles/ProductCard.css
  src/styles/ProductDetail.css
  src/styles/ShoppingCart.css
Labels: code-review

#307 [Group - 8] req 07
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/components/Cart.jsx
  src/components/CartItems.jsx
  src/components/CategoryList.jsx
  src/components/EmptyCart.jsx
  src/components/Home.jsx
  src/components/ProductCard.jsx
  src/components/ProductDetails.jsx
  src/components/Products.jsx
  src/components/Routes.jsx
  src/components/SearchBar.jsx
  src/img/car-trybe.png
  src/services/api.js
  src/services/serviceCart.js
Labels: enhancement

#337 [Group 10] - Feat: Requirement 10;
  src/App.js
  src/pages/Cart.jsx
  src/pages/ProductDetail.jsx
Labels: code-review

#334 [Group 8] req 9
  src/components/ProductDetails.jsx
  src/components/Products.jsx
  src/components/SearchBar.jsx
Labels: enhancement

#358 [Main Group 19] - CaioOk, MaxRudim, Murilo - Requirement12 - Finalize a compra vendo um resumo dela, preenchendo os seus dados e escolhendo a forma de pagamento
  src/App.js
  src/pages/Cart.js
  src/pages/FinishPurchase/PurchaseForm/BuyerInfo.js
  src/pages/FinishPurchase/PurchaseForm/PaymentMethod.js
  src/pages/FinishPurchase/PurchaseForm/index.js
  src/pages/FinishPurchase/ReviewProducts.js
  src/pages/FinishPurchase/index.js
Labels: code-review

#356 [Group 6] - Começa requisito 10 e corrige problemas no carrinho
  src/__tests__/requirement10.test.js
  src/components/AddToCart.jsx
  src/components/Header.jsx
  src/components/ItemOfCart.jsx
  src/components/ProductCard.jsx
  src/components/ProductInfo.jsx
  src/components/SearchBar.jsx
  src/pages/Home.jsx
  src/pages/ProductDetail.jsx
  src/pages/ShoppingCart.jsx
  src/services/shoppingCartService.js
Labels: code-review

#339 [ GRUPO 5 ] Em todas as telas com o ícone do carrinho, adicionar um número com a quantidade de produtos adicionados
  src/App.js
  src/pages/Home/index.js
  src/pages/ProductDetails/index.js
  src/pages/ShoppingCart.js
Labels: code-review

#375 [ Group15 ] Requirement15
  src/components/CardProduct/index.jsx
  src/pages/Home.jsx
  src/pages/ProductDetails.jsx
Labels: code-review

#369 [Group 6] - Main group 6 requisito 12
  src/App.js
  src/__tests__/requirement12.test.js
  src/__tests__/requirement14.test.js
  src/components/AddToCart.jsx
  src/components/ItemOfCart.jsx
  src/components/ListaCheckout.jsx
  src/pages/Checkout.jsx
  src/pages/ShoppingCart.jsx
  src/services/shoppingCartService.js
Labels: code-review

#377 [Group 15] - Css Home page and Component CardProduct
  package-lock.json
  package.json
  src/App.js
  src/components/CardProduct/index.jsx
  src/components/CardProduct/styles.module.css
  src/components/CartItem/index.jsx
  src/pages/Cart.jsx
  src/pages/Home.jsx
  src/pages/ProductDetails.jsx
  src/pages/styles.module.css
  src/styles/globals.css
  src/utils/functions.js
Labels: code-review

#315 [ Group 12 ] Requirement 8
  package-lock.json
  src/Components/AddCart.jsx
  src/Components/CardItem.jsx
  src/Components/CartProduct.jsx
  src/Components/EmptyCart.jsx
  src/Pages/Home.js
  src/Pages/ProductDetails.js
  src/Pages/ShoppingCart.js
  src/styles/ProductDetails.css
  src/styles/home.css
Labels: code-review

#383 [Group 15] - Requisito 13
  src/App.js
Labels: code-review

#386 [Group 12] Requirement 12
  src/App.js
  src/Components/AddCart.jsx
  src/Components/CardItem.jsx
  src/Components/Form.jsx
  src/Components/Payment.jsx
  src/Components/Star.jsx
  src/Data.js
  src/Pages/Checkout.js
  src/Pages/ProductDetails.js
  src/Pages/ShoppingCart.js
  src/Pictures/Boleto.jpg
  src/Pictures/Cartao.jpg
  src/Pictures/EstrelaDourada.png
  src/Pictures/EstrelaTransparente.png
  src/styles/Star.css
  src/styles/checkout.css
Labels: code-review

#387 [Group 6] - Requisito 13
  src/components/Header.jsx
  src/components/ItemOfCart.jsx
  src/components/ListaCheckout.jsx
  src/components/ProductCard.jsx
  src/components/ProductInfo.jsx
  src/components/ProductList.jsx
  src/pages/Checkout.jsx
  src/pages/Home.jsx
  src/pages/ProductDetail.jsx
  src/pages/ShoppingCart.jsx
  src/services/shoppingCartService.js
Labels: code-review

#389 [Group 12] Fix: Requirement 12
  src/Components/Form.jsx
  src/Pages/ShoppingCart.js
Labels: code-review

#392 [ Group 12 ] Requirement 10
  src/Components/CartProduct.jsx
  src/Components/Form.jsx
  src/styles/home.css
Labels: code-review

#355 [Main Group 14] Requisito 15
  src/App.css
  src/components/ProductCard.jsx
  src/imagens/free.png
  src/pages/Home.jsx
  src/pages/ProductDetail.jsx
  src/styles/ProductDetail.css
Labels: code-review

#384 Main group 14 req 10
  src/components/CartCard.jsx
  src/components/ProductCard.jsx
  src/pages/ProductDetail.jsx
  src/pages/ShoppingCart.jsx
  src/services/api.js
  src/services/localStorage.js
  src/styles/CartCard.css
Labels: code-review

#405 [Group 15] - Css Product Details
  src/components/CardProduct/index.jsx
  src/components/CardProduct/styles.module.css
  src/pages/Home.jsx
  src/pages/ProductDetails.jsx
  src/pages/styles.module.css
  src/styles/globals.css
Labels: code-review

#416 [group-15]-req14
  src/App.js
  src/components/CardProduct/index.jsx
  src/components/CardProduct/styles.module.css
  src/components/CardProduct/workspace.code-workspace
  src/components/CartItem/index.jsx
  src/pages/ProductDetails.jsx
Labels: code-review

#418 [group-15]-fix-req-10/css-color
  src/components/CartItem/styles.module.css
  src/pages/Cart.jsx
Labels: code-review

#422 [group-15]-refact-fix-CartItem
  src/components/CartItem/index.jsx
Labels: code-review

#430 [Group 15] - Componentização
  src/components/Header/index.jsx
  src/components/Header/styles.module.css
  src/pages/Home.jsx
  src/pages/styles.module.css
Labels: code-review

#394 [Main group 14] fix req 11
  src/components/FrontPage.jsx
  src/components/Loading.jsx
  src/components/ProductCard.jsx
  src/components/ReviewForm.jsx
  src/imagens/starEmpty.png
  src/imagens/starSolid.png
  src/pages/ProductDetail.jsx
  src/styles/FrontPage.css
  src/styles/ProductDetail.css
Labels: code-review

#357 main-group-14-req-12
  src/App.js
  src/components/CartCard.jsx
  src/components/FrontPage.jsx
  src/pages/FinalizingPurchase.jsx
  src/pages/ProductDetail.jsx
  src/pages/ShoppingCart.jsx
  src/services/localStorage.js
Labels: code-review
